package org.serialthreads.transformer.strategies.frequent3;

import org.objectweb.asm.tree.AbstractInsnNode;
import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.JumpInsnNode;
import org.objectweb.asm.tree.LabelNode;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.analysis.AnalyzerException;
import org.serialthreads.transformer.classcache.IClassInfoCache;

import java.util.ArrayList;
import java.util.List;

import static org.objectweb.asm.Opcodes.GOTO;

/**
 * Method transformer for run methods.
 */
@SuppressWarnings("UnusedDeclaration")
class RunMethodTransformer extends MethodTransformer {
  /**
   * Constructor.
   *
   * @param clazz class to transform
   * @param method method to transform
   * @param classInfoCache class cache to use
   */
  protected RunMethodTransformer(ClassNode clazz, MethodNode method, IClassInfoCache classInfoCache) {
    super(clazz, method, classInfoCache);
  }

  /**
   * Transform method.
   *
   * @return Transformed method
   * @throws AnalyzerException In case of incorrect byte code of the original method
   */
  public MethodNode transform() throws AnalyzerException {
    shiftLocals();
    analyze();

    replaceRunReturns();
    var restores = insertCaptureAndRestoreCode(true);
    redirectRestoreLabelsOutsideTryCatch(restores);
    createRestoreHandlerRun(restores);
    addThreadAndFrame();
    fixMaxs();
    nameLocals();

    return method;
  }

  /**
   * For each restore label that falls inside a try-catch block range, create a pre-initialization
   * block placed outside the try-catch block range and redirect the restore entry to it.
   *
   * <p>Background: the ASM verifier merges exception handler states at the entry of every basic
   * block that is covered by a try-catch block. A restore label (generated by
   * {@code insertCaptureAndRestoreCode}) is inserted right after the interruptible method call,
   * so it lands inside the try-catch range. At the restore label's entry, locals that will be
   * read from the frame have not yet been initialized, causing a verification error.
   *
   * <p>The fix: place a <em>pre-init block</em> after the method body (outside all try-catch
   * block ranges). The pre-init block initializes those locals to their type defaults and then
   * jumps to the original restore label. The TABLESWITCH dispatcher then targets the pre-init
   * block instead of the restore label directly. This ensures the verifier sees initialized
   * locals at the restore label's entry (carried in via the GOTO from the pre-init block).
   *
   * @param restores Restore labels, modified in place so the TABLESWITCH targets pre-init blocks.
   */
  private void redirectRestoreLabelsOutsideTryCatch(List<LabelNode> restores) {
    if (method.tryCatchBlocks == null || method.tryCatchBlocks.isEmpty()) {
      return;
    }

    var methodCallsList = new ArrayList<>(interruptibleMethodCalls);
    var last = method.instructions.getLast();

    for (int i = 0; i < restores.size(); i++) {
      var restoreLabel = restores.get(i);
      if (restoreLabel == null) continue;

      // Check if this restore label falls inside any try-catch block range.
      boolean insideTryCatch = method.tryCatchBlocks.stream()
        .anyMatch(tcb -> isInRange(restoreLabel, tcb.start, tcb.end));
      if (!insideTryCatch) continue;

      // Get the metaInfo for the corresponding method call (needed for defaultInitLocals).
      var methodCall = methodCallsList.get(i);
      var metaInfo = metaInfos.get(methodCall);

      // Build the pre-init block: initialize locals to type defaults, then jump to restore label.
      // The pre-init block is appended at the very end of the method, after all try-catch ranges.
      var preInitLabel = new LabelNode();
      var preInitCode = new InsnList();
      preInitCode.add(preInitLabel);
      preInitCode.add(threadCode.defaultInitLocals(methodCall, metaInfo));
      preInitCode.add(new JumpInsnNode(GOTO, restoreLabel));

      method.instructions.insert(last, preInitCode);

      // Point the TABLESWITCH to the pre-init block, not the restore label.
      restores.set(i, preInitLabel);
    }
  }

  /**
   * Check if an instruction lies strictly between two labels in the instruction list.
   *
   * @param instruction Instruction to locate.
   * @param start Label that begins the range (exclusive).
   * @param end Label that ends the range (exclusive).
   * @return True if {@code instruction} is between {@code start} and {@code end}.
   */
  private boolean isInRange(AbstractInsnNode instruction, LabelNode start, LabelNode end) {
    for (var current = start.getNext(); current != null && current != end; current = current.getNext()) {
      if (current == instruction) {
        return true;
      }
    }
    return false;
  }

  /**
   * Insert frame restoring code at the begin of the run() method.
   *
   * @param restores Labels pointing to the generated restore codes for method calls.
   */
  private void createRestoreHandlerRun(List<LabelNode> restores) {
    if (restores.isEmpty()) {
      logger.debug("    No restore handler needed for run");
      return;
    }

    logger.debug("    Creating restore handler for run");

    var instructions = new InsnList();

    // thread = this.$$thread$$;
    instructions.add(threadCode.getRunThread(clazz.name, localThread));
    // frame = this.$$frame$$;
    instructions.add(threadCode.getRunFrame(clazz.name, localFrame));

    // No previous frame needed in run, because there may not be a previous frame.

    // Add label for first call of run() at index -1, see "startIndex" below.
    // Empty frames are expected to have method == -1.
    var startRun = new LabelNode();
    restores.add(0, startRun);

    instructions.add(restoreCodeDispatcher(localFrame, restores, -1));

    // Dummy startup code to avoid check of thread.serializing.
    instructions.add(startRun);

    // Reset method to 0 for the case that there is just one normal restore code (except startRun),
    // because if there is just one normal restore code, the method index will not be captured.
    // So we set the correct one (0) for this case.
    if (restores.size() == 2) {
      instructions.add(threadCode.setMethod(localFrame, 0));
    }
    // Continue with normal code.

    method.instructions.insertBefore(method.instructions.getFirst(), instructions);
  }
}
