package org.serialthreads.transformer;

/**
 * Byte code transformer.
 */
public interface ITransformer {
  /**
   * Check generated byte code?.
   */
  void check();

  /**
   * Execute byte code transformation on a class.
   *
   * @param byteCode byte code of class to be transformed
   */
  byte[] transform(byte[] byteCode) throws NotTransformableException;
}
