package org.serialthreads.transformer.strategies.frequent2;

import org.objectweb.asm.tree.ClassNode;
import org.objectweb.asm.tree.InsnList;
import org.objectweb.asm.tree.MethodNode;
import org.objectweb.asm.tree.analysis.AnalyzerException;
import org.serialthreads.transformer.classcache.IClassInfoCache;

/**
 * Method transformer for concrete methods.
 */
@SuppressWarnings({"UnusedAssignment"})
class OriginalMethodTransformer extends MethodTransformer {
  /**
   * Constructor.
   *
   * @param clazz class to transform
   * @param method method to transform
   * @param classInfoCache class cache to use
   */
  protected OriginalMethodTransformer(ClassNode clazz, MethodNode method, IClassInfoCache classInfoCache) {
    super(clazz, method, classInfoCache);
  }

  /**
   * Transform method.
   *
   * @return Transformed method
   * @throws AnalyzerException In case of incorrect byte code of the original method
   */
  public MethodNode transform() throws AnalyzerException {
    shiftLocals();
    nameAddedLocals();
    analyze();

    insertCaptureCode();
    createRestoreHandlerMethod();
    fixMaxs();

    return method;
  }

  /**
   * Insert frame restoring code at the begin of an interruptible method.
   */
  private void createRestoreHandlerMethod() {
    logger.debug("    Creating restore handler for method");

    final int localThread = localThread();
    final int localPreviousFrame = localPreviousFrame();
    final int localFrame = localFrame();

    InsnList getFrame = new InsnList();
    // previousFrame = thread.frame;
    getFrame.add(threadCode.getPreviousFrame(localThread, localPreviousFrame));
    // frame = previousFrame.next; // etc.
    getFrame.add(threadCode.getNextFrame(localPreviousFrame, localFrame, true));

    // TODO 2009-11-26 mh: remove me?
    InsnList restoreCode = new InsnList();
    // thread.frame = frame;
    restoreCode.add(threadCode.setFrame(localThread, localFrame));

    // insert generated byte code
    insertMethodGetThreadStartCode(localThread, getFrame, restoreCode);
  }
}
